databases:
  - name: postgres
    ipAllowList: []
    databaseName: interview_experience
    user: interview_experience

services:
  - type: web
    name: interview_experience
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false